- name: Arch Setup Playbook2 - After Reboot
  gather_facts: no
  hosts: localhost

  tasks:

    - name: Ensure synology sync directory exists.
      file:
        dest: $HOME/synology_drive
        mode: 0700
        state: directory
      tags:
        - synology-drive

    - name: Ensure directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0700'
      loop:
        - "$HOME/synology_drive"
        - "$HOME/sync"

    - name: Add rime sync directory setting if NOT exists
      lineinfile:
        path: $HOME/.local/share/fcitx5/rime/installation.yaml 
        line: 'sync_dir: "/home/fdong/synology_drive/rime_sync"'
        insertbefore: EOF 
        state: present



