- name: Arch Packages Playbook
  gather_facts: no
  hosts: localhost

  tasks:

    # 1. Install packages & fonts
    # 2. Refresh font cache
    # 3. Install advcpmv
    # 4. Clone dotfiles from github

    - name: 1] Install packages and fonts
      become: yes
      become_user: aur_builder
      kewlfft.aur.aur:
        use: yay
        state: present
        name: "{{ item }}"
      loop: "{{ packages }}"
      vars:
        packages:
          # Emulator
          - kitty
          - wezterm
          #
          # dotfiles
          - stow
          #
          # Search
          - fd              # find entries in filesystem
          - ripgrep         # current directory recursively searches for a regex pattern
          - fzf             # command-line fuzzy finder
          #
          # Helper
          - tldr            # tong long don't read
          - man-db          # man page database
          - pkgfile         # "command not found" hook
          #
          # Tool
          - zoxide          # smart cd command
          - eza             # file icons
          #
          # Editor
          - neovim
          #
          # Utility
          - rsync           # file copying tool
          - neofetch        # cli system information
          - detox           # remove space char within filename
          - duf             # disk usage
          - xdg-ninjia      # home directory cleaning suggestion
          - wlr-randr       # Wayland refresh rate
          #
          # Compression
          - unzip
          - rar
          #
          # Clipboard
          - wl-clipboard    # wayland
          - xclip           # X11
          #
          # Hotkey
          - sxhkd           # X11 hotkey deamon
          #          - vim-fcitx
          - wev             # obtain key number from terminal
          - jq              # json parser, for hyprland cfg, quiting scratchpad befor switch workspace
          - mokutil         # for checking BIOS secure boot status
          #
          # language
          - luarocks        # requirement for Neovim Neorg
          #
          # Dependency
          - patch           # for advcpmv
          - gvfs-smb        # enable nemo/nautilus to connect smb share folds
          #
          # GUI
          - nemo            # GTK Cinnamon file manager, fork of GNOME files (Nautilus)
          - synology-drive
          #
          # Browser
          - firefox
          - brave-bin
          - vivaldi
          - thorium-browser-bin
          #
          # Fonts
          - fontconfig
          - noto-fonts
          - noto-fonts-cjk
          - noto-fonts-emoji
          - noto-fonts-extra
          - ttf-hack-nerd
          - ttf-sourcecodepro-nerd
          - ttf-jetbrains-mono-nerd
          - ttf-mononoki-nerd
      tags:
        - package

    - name: 2] Refresh font cache
      command: fc-cache -fv
      tags:
        - font

    - name: 3] check whether advcpmv installed
      stat:
        path: "/usr/local/bin/advcp"
      register: advcpmv_installed
      tags:
        - advcpmv

    - name: 3] Install advcpmv - cp / mv with progress bar & speed indicator
      shell: curl https://raw.githubusercontent.com/jarun/advcpmv/master/install.sh --create-dirs -o ./advcpmv/install.sh && (cd advcpmv && sh install.sh)
      when: not advcpmv_installed.stat.exists
      tags:
        - advcpmv

    - name: 3] Install advcpmv - move runable to runtime path
      become: yes
      shell: |
        mv ./advcpmv/advcp /usr/local/bin/ ;
        mv ./advcpmv/advmv /usr/local/bin/
      when: not advcpmv_installed.stat.exists
      tags:
        - advcpmv

    - name: 3] Remove ./advcpmv directory after installation
      file:
        path: ./advcpmv
        state: absent
      when: not advcpmv_installed.stat.exists
      tags:
        - advcpmv

    # - name: Install fonts packages <font>
    #   become: yes
    #   become_user: aur_builder
    #   kewlfft.aur.aur:
    #     use: yay
    #     state: present
    #     name: "{{ item }}"
    #   loop: "{{ packages }}"
    #   vars:
    #     packages:
    #       - fontconfig
    #       - noto-fonts
    #       - noto-fonts-cjk
    #       - noto-fonts-emoji
    #       - noto-fonts-extra
    #       - ttf-hack-nerd
    #       - ttf-sourcecodepro-nerd
    #       - ttf-jetbrains-mono-nerd
    #       - ttf-mononoki-nerd
    #   tags:
    #     - font

    - name: 4] check dotfile directory
      stat:
        path: "~/dotfiles"
      register: dotfiles_dir
      tags:
        - dotfile

    - name: 4] clone dotfiles
      git:
        repo: "git@github.com:curelesss/dotfiles.git"
        dest: "~/dotfiles"
      when: not dotfiles_dir.stat.exists
      tags:
        - dotfile





